const C=window.TASQUINHA_SUPABASE;const sb=window.supabase.createClient(C.url,C.key);const $=s=>document.querySelector(s);let cats=[],items=[];
async function session(){const r=await sb.auth.getSession();if(r.data.session){$("#auth").classList.add("hidden");$("#panel").classList.remove("hidden");$("#logout").classList.remove("hidden");loadAll()}else{$("#auth").classList.remove("hidden");$("#panel").classList.add("hidden")}}
async function loadAll(){const r=await Promise.all([sb.from("restaurant_settings").select("*").limit(1).maybeSingle(),sb.from("menu_categories").select("*").order("sort_order"),sb.from("menu_items").select("*").order("sort_order"),sb.from("daily_dishes").select("*").order("dish_date",{ascending:false}),sb.from("gallery").select("*").order("sort_order"),sb.from("orders").select("*").order("created_at",{ascending:false})]);cats=r[1].data||[];items=r[2].data||[];const s=r[0].data;if(s){$("#sName").value=s.name||"";$("#sPhone").value=s.phone||"";$("#sWhatsApp").value=s.whatsapp||"";$("#sEmail").value=s.email||"";$("#sAdminEmail").value=s.admin_email||"";$("#sAddress").value=s.address||"";$("#sHours").value=s.hours||"";$("#sMaps").value=s.maps_url||""}$("#iCategory").innerHTML=cats.map(x=>"<option value='"+x.id+"'>"+x.name+"</option>").join("");renderMenu();renderDaily(r[3].data||[]);renderGallery(r[4].data||[]);renderOrders(r[5].data||[])}
function renderMenu(){$("#menuList").innerHTML=cats.map(c=>"<h3>"+c.name+"</h3>"+items.filter(i=>i.category_id===c.id).map(i=>"<div class='item'><div><b>"+i.name+"</b><br>"+((i.price_cents||0)/100).toFixed(2)+" € "+(i.sold_out?"· ESGOTADO":"")+(i.is_specialty?" · ESPECIALIDADE":"")+"</div><button class='danger' onclick=\"removeItem('"+i.id+"')\">Apagar</button></div>").join("")).join("")}
async function removeItem(id){if(!confirm("Apagar este prato?"))return;await sb.from("menu_items").delete().eq("id",id);loadAll()}
function renderDaily(rows){$("#dailyList").innerHTML=rows.map(d=>"<div class='item'><div><b>"+d.dish_date+"</b> · "+d.name+"<br>"+(d.published?"Publicado":"Oculto")+"</div><button class='danger' onclick=\"deleteDaily('"+d.id+"')\">Apagar</button></div>").join("")}
async function deleteDaily(id){if(!confirm("Apagar prato do dia?"))return;await sb.from("daily_dishes").delete().eq("id",id);loadAll()}
function renderGallery(rows){$("#galleryList").innerHTML=rows.map(g=>"<div class='gitem'><div><img class='photo' src='"+g.image_url+"' alt=''><br>"+(g.caption||"")+"</div><button class='danger' onclick=\"deleteGallery('"+g.id+"')\">Apagar</button></div>").join("")}
function renderOrders(rows){$("#ordersList").innerHTML=rows.length?rows.map(o=>"<div class='item'><div><b>"+(o.customer_name||"Cliente")+"</b> · "+new Date(o.created_at).toLocaleString("pt-PT")+"<br>"+(o.customer_phone||"")+"<br>"+JSON.stringify(o.items)+"<br>Estado: <select onchange=\"setOrderStatus('"+o.id+"',this.value)\"><option "+(o.status==="new"?"selected":"")+" value='new'>Novo</option><option "+(o.status==="contacted"?"selected":"")+" value='contacted'>Contactado</option><option "+(o.status==="confirmed"?"selected":"")+" value='confirmed'>Confirmado</option><option "+(o.status==="completed"?"selected":"")+" value='completed'>Concluído</option><option "+(o.status==="cancelled"?"selected":"")+" value='cancelled'>Cancelado</option></select><br>"+(o.notes||"")+"</div></div>").join(""):"<p>Sem pedidos.</p>"}
async function setOrderStatus(id,status){const r=await sb.from("orders").update({status}).eq("id",id);if(r.error)alert(r.error.message)}
async function deleteGallery(id){if(!confirm("Apagar foto?"))return;await sb.from("gallery").delete().eq("id",id);loadAll()}
$("#login").onclick=async()=>{const r=await sb.auth.signInWithPassword({email:$("#email").value,password:$("#password").value});if(r.error)$("#authMsg").textContent=r.error.message;else session()};
$("#reset").onclick=async()=>{const email=$("#email").value.trim();if(!email)return $("#authMsg").textContent="Coloca o email primeiro.";const r=await sb.auth.resetPasswordForEmail(email,{redirectTo:location.href});$("#authMsg").textContent=r.error?r.error.message:"Email de recuperação enviado."};
$("#signup").onclick=async()=>{const r=await sb.auth.signUp({email:$("#email").value,password:$("#password").value});$("#authMsg").textContent=r.error?r.error.message:"Conta criada. Confirme o email se solicitado e depois entre."};
$("#logout").onclick=async()=>{await sb.auth.signOut();session()};
$("#saveSettings").onclick=async()=>{const q=await sb.from("restaurant_settings").select("id").limit(1).single();const p={name:$("#sName").value,phone:$("#sPhone").value,whatsapp:$("#sWhatsApp").value,email:$("#sEmail").value,admin_email:$("#sAdminEmail").value,address:$("#sAddress").value,hours:JSON.stringify($("#sHours").value),maps_url:$("#sMaps").value,updated_at:new Date().toISOString()};const r=await sb.from("restaurant_settings").update(p).eq("id",q.data.id);alert(r.error?r.error.message:"Dados guardados.")};
$("#itemForm").onsubmit=async e=>{e.preventDefault();const r=await sb.from("menu_items").insert({category_id:$("#iCategory").value,name:$("#iName").value,description:$("#iDesc").value,price_cents:Math.round((Number($("#iPrice").value)||0)*100),image_url:$("#iImage").value||null,sold_out:$("#iSold").checked,is_specialty:$("#iSpecial").checked,active:true,sort_order:items.length+1});if(r.error)alert(r.error.message);else{e.target.reset();loadAll()}};
$("#saveDaily").onclick=async()=>{const r=await sb.from("daily_dishes").insert({dish_date:$("#dDate").value,name:$("#dName").value,description:$("#dDesc").value,price_cents:Math.round((Number($("#dPrice").value)||0)*100),image_url:$("#dImage").value||null,published:$("#dPublished").checked});alert(r.error?r.error.message:"Prato do dia publicado.");loadAll()};
$("#galleryForm").onsubmit=async e=>{e.preventDefault();const f=$("#gFile").files[0];if(!f)return;const path="gallery/"+Date.now()+"-"+f.name.replace(/[^a-zA-Z0-9._-]/g,"-");const up=await sb.storage.from("restaurant-media").upload(path,f,{upsert:false});if(up.error)return alert(up.error.message);const url=sb.storage.from("restaurant-media").getPublicUrl(path).data.publicUrl;const r=await sb.from("gallery").insert({image_url:url,caption:$("#gCaption").value,sort_order:Date.now(),active:true});alert(r.error?r.error.message:"Foto carregada.");e.target.reset();loadAll()};
document.querySelectorAll(".tabs button").forEach(b=>b.onclick=()=>{document.querySelectorAll(".tab").forEach(x=>x.classList.add("hidden"));$("#"+b.dataset.tab).classList.remove("hidden")});session();